name: "Run Test Image in ECR"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-scan:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/test-image-in-ecr.yml
    with:
      working_directory: "."
      dockerfile: "Dockerfile"
      image_name: "hello-world"
      image_tag: "0.0.1"
      trivy_tag: "0.69.3"
    secrets:
      AWS_ECR_ACCOUNT_ID: ${{ secrets.AWS_ECR_ACCOUNT_ID }}
      ROLE_TO_ASSUME: ${{ secrets.ROLE_TO_ASSUME }}
