name: Checkov Scan

on:
  push:
    branches:
      - feature/README-changes
  pull_request:
    branches:
      - feature/README-changes

permissions:
  actions: read
  contents: read
  id-token: write
  security-events: write

jobs:
  checkov-scan:
    uses: Home-Office-Digital/core-cloud-workflow-checkov-sast-scan/.github/workflows/checkov-scan-base.yaml@feature/checkov-sarif-file-test
